# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2aadcfa742fbddabbdaa94e2e7ebb2c90df1aefa167317170b11cb0bcb02efdee94b3ff9f8aa10095c505591b20790cc976630ff4a72904345fdcf2ed50f65f

test:
  secret_key_base: a49f5819d438cd15835e41485d3c662cea77215f1e9050a2a53aab9d06ba7ca937dad4162bb3569f93b786f1f3eb2f45c792ff8bf85155c6d67f3c9baa03bfe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
